### ISSUE TITLE
System cannot find the files

### ISSUE THREAD

**Issue by yahav10** [bgeron/diff-pdf-visually#1]
Hi, I can't compare 2 PDF files and I'm getting the error of:

> FileNotFoundError: [WinError 2] The system cannot find the file specified

Although, the file paths are correct. I also tried to run the IDE as Administrator but without success.
I should open the file with the permission of "R/W" or it is enough to add the path as is?

**Comment by bgeron** [comment]
Hm, interesting. No administrator access should be required.  I haven't tested at all on Windows, and unfortunately at the moment I don't have access to a Windows system either. If you can run with `-vvv`, that will print the commands run, which may also give some insight into what's going wrong. Do you happen to have a backtrace, so we can see what line the error occurs on?

Just checking: did you install `pdfcairo` and ImageMagick?

**Comment by yahav10** [comment]
> Just checking: did you install `pdfcairo` and ImageMagick?
Yes, but still getting this error.

How can I run this script with `-vvv`?

**Comment by bgeron** [comment]
On Linux, pip installs scripts in the right place so you can just use 'diff-pdf-visually'. That doesn't seem to work on windows, but you can probably use python -m, e.g. "python -m diff_pdf_visually -vvv a.pdf b.pdf" On my Windows install that runs it in Python 3. Note the underscores instead of dashes. 

I tried installing pdftocairo, but I've not been able to run it just as "pdftocairo" from the command line, and I get exactly the same error that you're getting. I imagine it might be installable in Windows Subsystem for Linux but I don't have windows 10 at hand.

Were you running diff-pdf-visually from IDLE before? There's a way to run it from IDLE, I don't have a laptop at hand but I can look it up again. You'd still need to be able to run pdftocairo though of course.

Let me know!

**Comment by squirrelboot** [comment]
I am having this same problem. 

I can provide more specific info though:

`Temporary directory: C:\Users\sqboot\AppData\Local\Temp\diffpdfbzfxlraz
  Converting each page of the PDFs to an image...
Traceback (most recent call last):
  File "c:\users\sqboot\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "main", mod_spec)
  File "c:\users\sqboot\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\sqboot\AppData\Roaming\Python\Python37\Scripts\diff-pdf-visually.exe\__main__.py", line 9, in <module>
  File "C:\Users\sqboot\AppData\Roaming\Python\Python37\site-packages\diff_pdf_visually\__main__.py", line 70, in main
    time_to_inspect=args.time):
  File "C:\Users\sqboot\AppData\Roaming\Python\Python37\site-packages\diff_pdf_visually\diff.py", line 103, in pdfdiff
    a_i = a_i_.result()
  File "c:\users\sqboot\appdata\local\programs\python\python37\lib\concurrent\futures\_base.py", line 432, in result
    return self.get_result()
  File "c:\users\sqboot\appdata\local\programs\python\python37\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "c:\users\sqboot\appdata\local\programs\python\python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\sqboot\AppData\Roaming\Python\Python37\site-packages\diff_pdf_visually\diff.py", line 32, in pdftopng
    check=True,
  File "C:\Users\sqboot\AppData\Roaming\Python\Python37\site-packages\diff_pdf_visually\diff.py", line 166, in verbose_run
    return subprocess.run(args, *restargs, **kw)
  File "c:\users\sqboot\appdata\local\programs\python\python37\lib\subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\users\sqboot\appdata\local\programs\python\python37\lib\subprocess.py", line 775, in __init
    restore_signals, start_new_session)
  File "c:\users\sqboot\appdata\local\programs\python\python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified`


Cleaner paste:
https://pastebin.com/vdegE0HA

**Comment by squirrelboot** [comment]
Would really really appreciate some feedback if you can. I would really like to use this for a project!

**Comment by bgeron** [comment]
The problem seems to be that when we try to start `pdftocairo` with `subprocess.run`, Windows can't find `pdftocairo`. I've tried to install that tool on Windows and failed. If you managed: can you run it just by typing `pdftocairo` in `cmd`?

I think there's a good chance that everything just works under Windows Subsystem for Linux. I don't have Windows 10 myself so I can't try, but it seems to be essentially lightweight Ubuntu on Windows. If you have that, then you should be able to install `pdftocairo` and ImageMagick (for `convert`) with just `apt-get update`, then `apt-get install poppler-utils imagemagick`. Might have to enable the universe repositories. 

Let me know!

**Comment by squirrelboot** [comment]
Even in Linux I get issues:

`diff-pdf-visually a.pdf b.pdf
  Temporary directory: /tmp/diffpdfhkhuea_s
  Converting each page of the PDFs to an image...
  PDFs have same number of pages. Checking each pair of converted images...
Traceback (most recent call last):
  File "/usr/local/bin/diff-pdf-visually", line 11, in <module>
    sys.exit(__main__.main())
  File "/usr/local/lib/python3.5/dist-packages/diff_pdf_visually/__main__.py", line 70, in main
    time_to_inspect=args.time):
  File "/usr/local/lib/python3.5/dist-packages/diff_pdf_visually/diff.py", line 124, in pdfdiff
    s = imgdiff(pageapath, pagebpath, diffpath, logpath, (verbosity > VERB_PRINT_CMD))
  File "/usr/local/lib/python3.5/dist-packages/diff_pdf_visually/diff.py", line 54, in imgdiff
    stderr=subprocess.STDOUT,
  File "/usr/local/lib/python3.5/dist-packages/diff_pdf_visually/diff.py", line 166, in verbose_run
    return subprocess.run(args, *restargs, **kw)
  File "/usr/lib/python3.5/subprocess.py", line 383, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'compare'`

Clean paste:
https://pastebin.com/gM4Fj5zW

Note, it says no such file or directory: 'compare'. I could create it, but where?

**Comment by bgeron** [comment]
compare is a program that should be part of ImageMagick. Funky name for a program eh. Do you get it when you install ImageMagick?

**Comment by bgeron** [comment]
Closing because of no activity.

**Comment by plumbdata66** [comment]
Hi,
I am having the exact problems as above (FileNotFoundError) in Windows10.. 
I have installed the Poppler and ImageMagick...
Is this problem still unresolved on Windows platform ?

many thanks

**Comment by bgeron** [comment]
Hi Absar,

The Windows instructions are adapted from someone who said it worked for them on Windows. But maybe I copied some instructions wrong. They installed poppler inside the site-packages directory, maybe that helps. Actually I suggest trying the Windows Subsystem for Linux path, I really think that should work. With WSL it’s much earlier for programs to find each other and that seems to be the problem here. There’s WSL installation instructions in the README. Could you try that?

Cheers, Bram


Am Mo, 15. Jun 2020, um 13:10, schrieb Absar Faruqi:

**Comment by plumbdata66** [comment]
Many thanks Bram for your advice..Cheers

**Comment by bgeron** [comment]
Let me know if it works for you!

Am Do, 18. Jun 2020, um 03:22, schrieb Absar Faruqi:

**Comment by DukeYe** [comment]
@plumbdata66 Is there a solution to this problem? I am also facing the same problem.

**Comment by bgeron** [comment]
Hi @DukeYe , perhaps I can help. Did you install ImageMagick? As `diff-pdf-visually` 100% depends on it for its functioning. Have you tried / are you open to trying the WSL suggestion in my June 18 2020 message?

Cheers, Bram
